data <- read.table("household_power_consumption.txt", sep = ";", header = T)
head(data)
library("dplyr")
png("plot2.png", 480,480)
df <- mutate(data, formattedDate2 = as.Date(data$Date, format = "%d/%m/%Y"))
df <- filter(df, df$formattedDate2 == "2007-02-01" | df$formattedDate2 == "2007-02-02")
df$day <- weekdays(df$formattedDate)
numericgpa <- as.numeric(as.character(df$Global_active_power))
df$datetime11 <- strptime(paste(df$Date, df$Time), format = "%d/%m/%Y %H:%M:%S")
plot(df$datetime11, numericgpa, type = "l", xlab = "", ylab = "Global Active Power", yaxt = "n")
axis(side = 2, ylab = "Global Active Power", lwd = 2.5)
dev.off()