data <- read.table("household_power_consumption.txt", sep = ";", header = T)
head(data)
library("dplyr")
png("plot4.png", 480,480)
df <- mutate(data, formattedDate2 = as.Date(data$Date, format = "%d/%m/%Y"))
df <- filter(df, df$formattedDate2 == "2007-02-01" | df$formattedDate2 == "2007-02-02")
df$day <- weekdays(df$formattedDate)
numericgpa <- as.numeric(as.character(df$Global_active_power))
df$datetime11 <- strptime(paste(df$Date, df$Time), format = "%d/%m/%Y %H:%M:%S")

par(mfcol = c(2,2))
plot(df$datetime11, numericgpa, type = "l", xlab = "", ylab = "Global Active Power", lwd = 1.5, yaxt = "n")
axis(side = 2, ylab = "Global Active Power", lwd = 2.5)
plot(df$datetime11, as.numeric(as.character(df$Sub_metering_1)), type = "l", col = "black", ylim = c(0, max(as.numeric(as.character(df$Sub_metering_1)), as.numeric(as.character(df$Sub_metering_2)), as.numeric(as.character(df$Sub_metering_3)))), xlab = "", ylab = "Energy sub metering", lwd = 1.5)
lines(df$datetime11, as.numeric(as.character(df$Sub_metering_3)), col = "blue",  lwd = 1.5)
lines(df$datetime11, as.numeric(as.character(df$Sub_metering_2)), col = "red" , lwd = 1.5)
axis(side = 2, ylab = "Energy sub metering", lwd = 2.5)
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=1.5, col=c("black", "red", "blue"))
plot(df$datetime11, as.numeric(as.character(df$Voltage)), type = "l", lwd = 1.5, xlab = "datetime", ylab = "Voltage")
axis(side = 2, ylab = "Voltage", lwd = 2.5)
plot(df$datetime11, as.numeric(as.character(df$Global_reactive_power)), type = "l", lwd = 1.5, ylab = "Global_reactive_power", xlab = "datetime")
axis(side = 2, ylab = "Global_reactive_power", lwd = 2.5)

dev.off()