data <- read.table("household_power_consumption.txt", sep = ";", header = T)
head(data)
library("dplyr")
png("plot3.png", 480,480)
df <- mutate(data, formattedDate2 = as.Date(data$Date, format = "%d/%m/%Y"))
df <- filter(df, df$formattedDate2 == "2007-02-01" | df$formattedDate2 == "2007-02-02")
df$day <- weekdays(df$formattedDate)
numericgpa <- as.numeric(as.character(df$Global_active_power))
df$datetime11 <- strptime(paste(df$Date, df$Time), format = "%d/%m/%Y %H:%M:%S")
plot(df$datetime11, as.numeric(as.character(df$Sub_metering_1)), type = "l", col = "black", ylim = c(0, max(as.numeric(as.character(df$Sub_metering_1)), as.numeric(as.character(df$Sub_metering_2)), as.numeric(as.character(df$Sub_metering_3)))), xlab = "", lwd = 2.5, yaxt = "n", ylab = "Energy sub metering")
lines(df$datetime11, as.numeric(as.character(df$Sub_metering_3)), col = "blue",  lwd = 2.5, yaxt = "n")
lines(df$datetime11, as.numeric(as.character(df$Sub_metering_2)), col = "red" , lwd = 2.5, yaxt = "n")
axis(side = 2, lwd = 2.5)
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))

dev.off()